In [1]:
#  Ebnable HTML/CSS 
from IPython.core.display import HTML
HTML("<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'><style>div.attn { font-family: 'Helvetica Neue'; font-size: 30px; line-height: 40px; color: #FFFFFF; text-align: center; margin: 30px 0; border-width: 10px 0; border-style: solid; border-color: #5AAAAA; padding: 30px 0; background-color: #DDDDFF; }hr { border: 0; background-color: #ffffff; border-top: 1px solid black; }hr.major { border-top: 10px solid #5AAA5A; }hr.minor { border: none; background-color: #ffffff; border-top: 5px dotted #CC3333; }div.bubble { width: 65%; padding: 20px; background: #DDDDDD; border-radius: 15px; margin: 0 auto; font-style: italic; color: #f00; }em { color: #AAA; }div.c1{visibility:hidden;margin:0;height:0;}div.note{color:red;}</style>")

___
Enter Team Member Names here (double click to edit):

- Name 1: Alexandra Fisher
- Name 2: James Hancock
- Name 3:


# In Class Assignment One
In the following assignment you will be asked to fill in python code and derivations for a number of different problems. Please read all instructions carefully and turn in the rendered notebook (or HTML of the rendered notebook)  before the end of class (or right after class). The initial portion of this notebook is given before class and the remainder is given during class. Please answer the initial questions before class. Once class has started you may rework your answers as a team for the initial part of the assignment. 

## Contents
* <a href="#Loading">Loading the Data</a>
* <a href="#linearnumpy">Linear Regression</a>

**These portions are not yet accessible until the start of class:**
* <a href="#sklearn">Using Scikit Learn for Regression</a>
* <a href="#classification">Linear Classification</a>

________________________________________________________________________________________________________

<a id="Loading"></a>
## Loading the Data
Please run the following code to read in the "diabetes" dataset from sklearn's data loading module. 

This will load the data into the variable `ds`. `ds` is a dictionary object with fields like `ds.data`, which is a matrix of the continuous features in the dataset. The object is not a pandas dataframe. It is a numpy matrix. Each row is a set of observed instances, each column is a different feature. It also has a field called `ds.target` that is a continuous value we are trying to predict. Each entry in `ds.target` is a label for each row of the `ds.data` matrix. 

In [7]:
from sklearn.datasets import load_diabetes
import numpy as np
from __future__ import print_function


ds = load_diabetes()

# this holds the continuous feature data
# because ds.data is a matrix, there are some special properties we can access (like 'shape')
print('features shape:', ds.data.shape, 'format is:', ('rows','columns')) # there are 442 instances and 10 features per instance
print('range of target:', np.min(ds.target),np.max(ds.target))

features shape: (442L, 10L) format is: ('rows', 'columns')
range of target: 25.0 346.0


In [33]:
from pprint import pprint

# we can set the fields inside of ds and set them to new variables in python
pprint(ds.data) # prints out elements of the matrix
pprint(ds.target) # prints the vector (all 442 items)

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ..., 
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])
array([ 151.,   75.,  141.,  206.,  135.,   97.,  138.,   63.,  110.,
        310.,  101.,   69.,  179.,  185.,  118.,  171.,  166.,  144.,
         97.,  168.,   68.,   49.,   68.,  245.,  184.,  202.,  137.,
         85.,  131.,  283.,  129.,   59.,  341.,   87.,   65.,  102.,
        265.,  276.,  252.,   90.,  100.,   55.,   61.,   92.,  259.,
         53.,  190.,  142.,   75.,  

________________________________________________________________________________________________________
<a id="linearnumpy"></a>
## Using Linear Regression 
In the videos, we derived the formula for calculating the optimal values of the regression weights (you must be connected to the internet for this equation to show up properly):

$$ w = (X^TX)^{-1}X^Ty $$

where $X$ is the matrix of values with a bias column of ones appended onto it. For the diabetes dataset one could construct this $X$ matrix by stacking a column of ones onto the `ds.data` matrix. 

$$ X=\begin{bmatrix}
         & \vdots &        &  1 \\
        \dotsb & \text{ds.data} & \dotsb &  \vdots\\
         & \vdots &         &  1\\
     \end{bmatrix}
$$

**Question 1:** For the diabetes dataset, how many elements will the vector $w$ contain?

In [6]:
# Enter your answer here (or write code to calculate it)

w.count() 

# For the diabetes dataset, the vector w contains __________ number of elements

pprint(ds.target) # python print the vector (of all) # is this the answer?

pprint(w.data) # python print matrix elements for vector w # is this correct? 

NameError: name 'pprint' is not defined

________________________________________________________________________________________________________

**Exercise 1:** In the following empty cell, use this equation and numpy matrix operations to find the values of the vector $w$. You will need to be sure $X$ and $y$ are created like the instructor talked about in the video. Don't forget to include any modifications to $X$ to account for the bias term in $w$. You might be interested in the following functions:

- `np.hstack((mat1,mat2))` stack two matrices horizontally, to create a new matrix
- `np.ones((rows,cols))` create a matrix full of ones
- `my_mat.T` takes transpose of numpy matrix named `my_mat`
- `np.dot(mat1,mat2)` is matrix multiplication for two matrices
- `np.linalg.inv(mat)` gets the inverse of the variable `mat`

In [3]:
# Using the linear regression equation and numpy matrix operations
# Find the values of vector w for the diabetes dataset 
    # ds = load_diabetes()
    # ds.data = matrix elements
    # ds.target = vector (all 442 items)
        
# First - Create X by stacking column of ones onto ds.data matrix 
# np.ones((rows,cols)) # creates a matrix full of ones

######## CREATE mat1 STUCK ON ERRORS ############
            #mat1 = np.ones((rows,cols))
            #cols = 1
            #mat1 = np.ones((,1)) # a column of ones matrix = mat1
            #mat1 = np.ones((rows,),1)
            #s = (('rows',1), 
            #mat1 = np.ones(s)
            #mat1 = np.ones((,1), dtype=np.int)
                # >>> np.ones((5,), dtype=np.int)
                # array([1, 1, 1, 1, 1])
    
mat2 = ds.data # diabetes dataset matrix = mat2
X = np.hstack((mat1,mat2)) # horizontal stacking column of ones onto ds.data matrix to make matrix X

# Second - Create y
y = np.mat(y) # ???

# Third - Make sure to include modifications to X to account for the bias term in w

# linear regression assumption: y_hat = (w^T)*(X_hat)     # what is Transposed and what is not Transposed?
XTX = X.T.dot(X) # XTX = X_hat
XTy = X.T.dot(y) # XTy = y_hat

# Print values of regression weights using the 'print()' function in python
XTX_inv = np.linalg.inv(XTX) # inverse of matrix X_hat       
w = np.dot(XTX_inv, XTy) # solve for w 
pprint(w.data) # python print values of regression weights

# Print the count (#) of elements in vector w
        # n = np.count(w.data)  # ??? 
        # print(n)              # ???

n = np.count(w.data) # ??
print(n) # ??
n.show() # ??
        

# ----------------------------------------------------------------------------------- #
# Notes:
            # X = np.mat(x)
            # y = np.mat(y)
            # z = x*y
            # z
    # OR
            # z = np.dot(x,y)
# ----------------------------------------------------------------------------------- #  

NameError: name 'mat1' is not defined

In [ ]:
# Using scikit-learn for regression

# Classification

# logistic regression is a classification problem

